### ISSUE TITLE
Expand web app to full screen on mobile, use app install banners

### ISSUE THREAD

**Issue by ajhodges** [codeforgreenville/trackthetrolley-com#4]
Make the tracker map full-screen by default on mobile, add native app install banners for iOS/Android based on device type

https://developer.android.com/distribute/users/banners.html#related-resources
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

**Comment by invisionjeremy** [comment]
This was completed a while ago and never closed
