### ISSUE TITLE
Latest code in repo?

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trackthetrolley-com#7]
Went to look at repo and page didn't render correctly locally.   Found at least one difference in trolleytracker-marketing.js, VS the copy on trackthetrolley.com so wanted to check if all the latest code is in the repo before continuing?

**Comment by jeremywight** [comment]
It’s possible that they are out of sync and that the code in the repo
didn’t get updated, though I’m not certain. If it’s the .js that would
likely have been David.
